// Package scoring implements bumper-lanes weighted threshold scoring.
// This calculates scores from raw DiffStats JSON (from diff-viz library).
package scoring

import (
	"sort"
	"strings"

	"github.com/kylesnowschwartz/diff-viz/v2/diff"
)

// WeightedScore holds the bumper-lanes weighted score calculation.
type WeightedScore struct {
	Score          int `json:"score"`          // Total weighted score
	NewAdditions   int `json:"new_additions"`  // Lines added in new files
	EditAdditions  int `json:"edit_additions"` // Lines added in edited files
	FilesTouched   int `json:"files_touched"`  // Number of files changed
	ScatterPenalty int `json:"scatter"`        // Penalty for touching many files
	NetLines       int `json:"net_lines"`      // Additions minus deletions, excluding generated files
}

// Scoring constants (match threshold-calculator.sh)
const (
	newFileWeight        = 10 // 1.0x baseline (scaled x10 for integer math)
	editFileWeight       = 13 // 1.3x penalty (edits harder to review)
	scatterLowThreshold  = 6  // Medium penalty starts
	scatterHighThreshold = 11 // High penalty starts
	scatterPenaltyLow    = 10 // Points/file for 6-10 files
	scatterPenaltyHigh   = 30 // Points/file for 11+ files
	freeTier             = 5  // Files 1-5 are penalty-free
)

// generatedBasenames are lockfiles regenerated by tooling; nobody reads
// their diff, so their churn is not review burden.
var generatedBasenames = map[string]bool{
	"go.sum":            true,
	"package-lock.json": true,
	"yarn.lock":         true,
	"pnpm-lock.yaml":    true,
	"Gemfile.lock":      true,
	"Cargo.lock":        true,
}

// generatedSuffixes mark machine-written source.
var generatedSuffixes = []string{".lock", ".pb.go", "_generated.go", ".min.js", ".min.css"}

// IsGenerated reports whether a path's content is machine-written
// (lockfiles, codegen output, vendored trees) and therefore free to change.
func IsGenerated(path string) bool {
	base := path
	if i := strings.LastIndex(path, "/"); i >= 0 {
		base = path[i+1:]
	}
	if generatedBasenames[base] {
		return true
	}
	for _, suffix := range generatedSuffixes {
		if strings.HasSuffix(base, suffix) {
			return true
		}
	}
	return strings.HasPrefix(path, "vendor/") || strings.Contains(path, "/vendor/") ||
		strings.HasPrefix(path, "node_modules/") || strings.Contains(path, "/node_modules/")
}

// ModulePoints is a directory's share of the weighted score.
type ModulePoints struct {
	Module string // directory containing the changed files ("(root)" for top-level files)
	Points int
	Files  int // files with additions in this module
}

// ByModule aggregates weighted points per directory, ranked by points
// (module path as tiebreak). Same policy as Calculate: edits 1.3x, new
// files 1.0x, deletions free, generated files excluded. Scatter is a
// whole-diff penalty and is not attributed to modules, so module points
// sum to the score minus scatter (give or take per-file rounding).
func ByModule(stats *diff.StatsJSON) []ModulePoints {
	agg := map[string]*ModulePoints{}
	for _, f := range stats.Files {
		if IsGenerated(f.Path) || f.Adds == 0 {
			continue
		}
		module := "(root)"
		if i := strings.LastIndex(f.Path, "/"); i >= 0 {
			module = f.Path[:i+1]
		}
		m := agg[module]
		if m == nil {
			m = &ModulePoints{Module: module}
			agg[module] = m
		}
		weight := editFileWeight
		if f.New {
			weight = newFileWeight
		}
		m.Points += (f.Adds * weight) / 10
		m.Files++
	}

	modules := make([]ModulePoints, 0, len(agg))
	for _, m := range agg {
		modules = append(modules, *m)
	}
	sort.Slice(modules, func(i, j int) bool {
		if modules[i].Points != modules[j].Points {
			return modules[i].Points > modules[j].Points
		}
		return modules[i].Module < modules[j].Module
	})
	return modules
}

// Calculate computes bumper-lanes score from raw diff stats.
// New files get 1.0x weight, edits get 1.3x weight.
// Deletions are ignored (they reduce complexity, not add review burden).
// Generated files (lockfiles, codegen, vendored) score zero: their churn
// is mechanical, and billing it is how gates get uninstalled.
func Calculate(stats *diff.StatsJSON) *WeightedScore {
	var newAdd, editAdd, netLines int
	var filesWithAdditions int // Only count files that add lines (not pure deletions)

	for _, f := range stats.Files {
		if IsGenerated(f.Path) {
			continue
		}
		netLines += f.Adds - f.Dels
		if f.Adds > 0 {
			filesWithAdditions++
			if f.New {
				newAdd += f.Adds
			} else {
				editAdd += f.Adds
			}
		}
		// Files with only deletions (f.Adds == 0) don't count toward scatter
	}

	// Calculate scatter penalty (only for files with additions)
	var scatter int
	if filesWithAdditions >= scatterHighThreshold {
		scatter = (filesWithAdditions - freeTier) * scatterPenaltyHigh
	} else if filesWithAdditions >= scatterLowThreshold {
		scatter = (filesWithAdditions - freeTier) * scatterPenaltyLow
	}

	// Weighted score: (new x 10 + edit x 13) / 10 + scatter
	totalPoints := (newAdd * newFileWeight) + (editAdd * editFileWeight)
	score := (totalPoints / 10) + scatter

	return &WeightedScore{
		Score:          score,
		NewAdditions:   newAdd,
		EditAdditions:  editAdd,
		FilesTouched:   filesWithAdditions, // Only files with additions
		ScatterPenalty: scatter,
		NetLines:       netLines,
	}
}
